// Code generated by MockGen. DO NOT EDIT.
// Source: drain_observer.go
//
// Generated by this command:
//
//	mockgen -package clientcommon -source drain_observer.go -destination drain_observer_mock.go . DrainSignalObserver
//

// Package clientcommon is a generated GoMock package.
package clientcommon

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDrainSignalObserver is a mock of DrainSignalObserver interface.
type MockDrainSignalObserver struct {
	ctrl     *gomock.Controller
	recorder *MockDrainSignalObserverMockRecorder
	isgomock struct{}
}

// MockDrainSignalObserverMockRecorder is the mock recorder for MockDrainSignalObserver.
type MockDrainSignalObserverMockRecorder struct {
	mock *MockDrainSignalObserver
}

// NewMockDrainSignalObserver creates a new mock instance.
func NewMockDrainSignalObserver(ctrl *gomock.Controller) *MockDrainSignalObserver {
	mock := &MockDrainSignalObserver{ctrl: ctrl}
	mock.recorder = &MockDrainSignalObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrainSignalObserver) EXPECT() *MockDrainSignalObserverMockRecorder {
	return m.recorder
}

// ShouldStop mocks base method.
func (m *MockDrainSignalObserver) ShouldStop() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldStop")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// ShouldStop indicates an expected call of ShouldStop.
func (mr *MockDrainSignalObserverMockRecorder) ShouldStop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldStop", reflect.TypeOf((*MockDrainSignalObserver)(nil).ShouldStop))
}
