// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/service/history/taskdlq (interfaces: HistoryTaskDLQStore,TaskExecutor)
//
// Generated by this command:
//
//	mockgen -package taskdlq -destination interface_mock.go github.com/uber/cadence/service/history/taskdlq HistoryTaskDLQStore,TaskExecutor
//

// Package taskdlq is a generated GoMock package.
package taskdlq

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	persistence "github.com/uber/cadence/common/persistence"
)

// MockHistoryTaskDLQStore is a mock of HistoryTaskDLQStore interface.
type MockHistoryTaskDLQStore struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryTaskDLQStoreMockRecorder
	isgomock struct{}
}

// MockHistoryTaskDLQStoreMockRecorder is the mock recorder for MockHistoryTaskDLQStore.
type MockHistoryTaskDLQStoreMockRecorder struct {
	mock *MockHistoryTaskDLQStore
}

// NewMockHistoryTaskDLQStore creates a new mock instance.
func NewMockHistoryTaskDLQStore(ctrl *gomock.Controller) *MockHistoryTaskDLQStore {
	mock := &MockHistoryTaskDLQStore{ctrl: ctrl}
	mock.recorder = &MockHistoryTaskDLQStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistoryTaskDLQStore) EXPECT() *MockHistoryTaskDLQStoreMockRecorder {
	return m.recorder
}

// DeleteTasks mocks base method.
func (m *MockHistoryTaskDLQStore) DeleteTasks(ctx context.Context, request DeleteTasksRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTasks", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTasks indicates an expected call of DeleteTasks.
func (mr *MockHistoryTaskDLQStoreMockRecorder) DeleteTasks(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTasks", reflect.TypeOf((*MockHistoryTaskDLQStore)(nil).DeleteTasks), ctx, request)
}

// GetAckLevels mocks base method.
func (m *MockHistoryTaskDLQStore) GetAckLevels(ctx context.Context, shardID int) ([]AckLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAckLevels", ctx, shardID)
	ret0, _ := ret[0].([]AckLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAckLevels indicates an expected call of GetAckLevels.
func (mr *MockHistoryTaskDLQStoreMockRecorder) GetAckLevels(ctx, shardID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAckLevels", reflect.TypeOf((*MockHistoryTaskDLQStore)(nil).GetAckLevels), ctx, shardID)
}

// GetAckLevelsForPartition mocks base method.
func (m *MockHistoryTaskDLQStore) GetAckLevelsForPartition(ctx context.Context, shardID int, domainID, clusterAttributeScope, clusterAttributeName string) ([]AckLevel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAckLevelsForPartition", ctx, shardID, domainID, clusterAttributeScope, clusterAttributeName)
	ret0, _ := ret[0].([]AckLevel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAckLevelsForPartition indicates an expected call of GetAckLevelsForPartition.
func (mr *MockHistoryTaskDLQStoreMockRecorder) GetAckLevelsForPartition(ctx, shardID, domainID, clusterAttributeScope, clusterAttributeName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAckLevelsForPartition", reflect.TypeOf((*MockHistoryTaskDLQStore)(nil).GetAckLevelsForPartition), ctx, shardID, domainID, clusterAttributeScope, clusterAttributeName)
}

// GetTasks mocks base method.
func (m *MockHistoryTaskDLQStore) GetTasks(ctx context.Context, request GetTasksRequest) (GetTasksResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTasks", ctx, request)
	ret0, _ := ret[0].(GetTasksResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTasks indicates an expected call of GetTasks.
func (mr *MockHistoryTaskDLQStoreMockRecorder) GetTasks(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTasks", reflect.TypeOf((*MockHistoryTaskDLQStore)(nil).GetTasks), ctx, request)
}

// UpdateAckLevel mocks base method.
func (m *MockHistoryTaskDLQStore) UpdateAckLevel(ctx context.Context, request UpdateAckLevelRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAckLevel", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAckLevel indicates an expected call of UpdateAckLevel.
func (mr *MockHistoryTaskDLQStoreMockRecorder) UpdateAckLevel(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAckLevel", reflect.TypeOf((*MockHistoryTaskDLQStore)(nil).UpdateAckLevel), ctx, request)
}

// MockTaskExecutor is a mock of TaskExecutor interface.
type MockTaskExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockTaskExecutorMockRecorder
	isgomock struct{}
}

// MockTaskExecutorMockRecorder is the mock recorder for MockTaskExecutor.
type MockTaskExecutorMockRecorder struct {
	mock *MockTaskExecutor
}

// NewMockTaskExecutor creates a new mock instance.
func NewMockTaskExecutor(ctrl *gomock.Controller) *MockTaskExecutor {
	mock := &MockTaskExecutor{ctrl: ctrl}
	mock.recorder = &MockTaskExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskExecutor) EXPECT() *MockTaskExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockTaskExecutor) Execute(ctx context.Context, task persistence.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockTaskExecutorMockRecorder) Execute(ctx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockTaskExecutor)(nil).Execute), ctx, task)
}

// HandleErr mocks base method.
func (m *MockTaskExecutor) HandleErr(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleErr", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleErr indicates an expected call of HandleErr.
func (mr *MockTaskExecutorMockRecorder) HandleErr(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleErr", reflect.TypeOf((*MockTaskExecutor)(nil).HandleErr), err)
}
