// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: uber/cadence/shared/v1/error.proto

package sharedv1

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
	v11 "github.com/uber/cadence-idl/go/proto/admin/v1"
	v1 "github.com/uber/cadence-idl/go/proto/api/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CurrentBranchChangedError struct {
	CurrentBranchToken   []byte   `protobuf:"bytes,1,opt,name=current_branch_token,json=currentBranchToken,proto3" json:"current_branch_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CurrentBranchChangedError) Reset()         { *m = CurrentBranchChangedError{} }
func (m *CurrentBranchChangedError) String() string { return proto.CompactTextString(m) }
func (*CurrentBranchChangedError) ProtoMessage()    {}
func (*CurrentBranchChangedError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{0}
}
func (m *CurrentBranchChangedError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CurrentBranchChangedError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CurrentBranchChangedError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CurrentBranchChangedError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CurrentBranchChangedError.Merge(m, src)
}
func (m *CurrentBranchChangedError) XXX_Size() int {
	return m.Size()
}
func (m *CurrentBranchChangedError) XXX_DiscardUnknown() {
	xxx_messageInfo_CurrentBranchChangedError.DiscardUnknown(m)
}

var xxx_messageInfo_CurrentBranchChangedError proto.InternalMessageInfo

func (m *CurrentBranchChangedError) GetCurrentBranchToken() []byte {
	if m != nil {
		return m.CurrentBranchToken
	}
	return nil
}

type InternalDataInconsistencyError struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalDataInconsistencyError) Reset()         { *m = InternalDataInconsistencyError{} }
func (m *InternalDataInconsistencyError) String() string { return proto.CompactTextString(m) }
func (*InternalDataInconsistencyError) ProtoMessage()    {}
func (*InternalDataInconsistencyError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{1}
}
func (m *InternalDataInconsistencyError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InternalDataInconsistencyError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InternalDataInconsistencyError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InternalDataInconsistencyError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalDataInconsistencyError.Merge(m, src)
}
func (m *InternalDataInconsistencyError) XXX_Size() int {
	return m.Size()
}
func (m *InternalDataInconsistencyError) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalDataInconsistencyError.DiscardUnknown(m)
}

var xxx_messageInfo_InternalDataInconsistencyError proto.InternalMessageInfo

type EventAlreadyStartedError struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventAlreadyStartedError) Reset()         { *m = EventAlreadyStartedError{} }
func (m *EventAlreadyStartedError) String() string { return proto.CompactTextString(m) }
func (*EventAlreadyStartedError) ProtoMessage()    {}
func (*EventAlreadyStartedError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{2}
}
func (m *EventAlreadyStartedError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAlreadyStartedError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAlreadyStartedError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAlreadyStartedError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAlreadyStartedError.Merge(m, src)
}
func (m *EventAlreadyStartedError) XXX_Size() int {
	return m.Size()
}
func (m *EventAlreadyStartedError) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAlreadyStartedError.DiscardUnknown(m)
}

var xxx_messageInfo_EventAlreadyStartedError proto.InternalMessageInfo

type RemoteSyncMatchedError struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoteSyncMatchedError) Reset()         { *m = RemoteSyncMatchedError{} }
func (m *RemoteSyncMatchedError) String() string { return proto.CompactTextString(m) }
func (*RemoteSyncMatchedError) ProtoMessage()    {}
func (*RemoteSyncMatchedError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{3}
}
func (m *RemoteSyncMatchedError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoteSyncMatchedError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoteSyncMatchedError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoteSyncMatchedError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoteSyncMatchedError.Merge(m, src)
}
func (m *RemoteSyncMatchedError) XXX_Size() int {
	return m.Size()
}
func (m *RemoteSyncMatchedError) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoteSyncMatchedError.DiscardUnknown(m)
}

var xxx_messageInfo_RemoteSyncMatchedError proto.InternalMessageInfo

type RetryTaskV2Error struct {
	DomainId             string                  `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	WorkflowExecution    *v1.WorkflowExecution   `protobuf:"bytes,2,opt,name=workflow_execution,json=workflowExecution,proto3" json:"workflow_execution,omitempty"`
	StartEvent           *v11.VersionHistoryItem `protobuf:"bytes,3,opt,name=start_event,json=startEvent,proto3" json:"start_event,omitempty"`
	EndEvent             *v11.VersionHistoryItem `protobuf:"bytes,4,opt,name=end_event,json=endEvent,proto3" json:"end_event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *RetryTaskV2Error) Reset()         { *m = RetryTaskV2Error{} }
func (m *RetryTaskV2Error) String() string { return proto.CompactTextString(m) }
func (*RetryTaskV2Error) ProtoMessage()    {}
func (*RetryTaskV2Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{4}
}
func (m *RetryTaskV2Error) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RetryTaskV2Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RetryTaskV2Error.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RetryTaskV2Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryTaskV2Error.Merge(m, src)
}
func (m *RetryTaskV2Error) XXX_Size() int {
	return m.Size()
}
func (m *RetryTaskV2Error) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryTaskV2Error.DiscardUnknown(m)
}

var xxx_messageInfo_RetryTaskV2Error proto.InternalMessageInfo

func (m *RetryTaskV2Error) GetDomainId() string {
	if m != nil {
		return m.DomainId
	}
	return ""
}

func (m *RetryTaskV2Error) GetWorkflowExecution() *v1.WorkflowExecution {
	if m != nil {
		return m.WorkflowExecution
	}
	return nil
}

func (m *RetryTaskV2Error) GetStartEvent() *v11.VersionHistoryItem {
	if m != nil {
		return m.StartEvent
	}
	return nil
}

func (m *RetryTaskV2Error) GetEndEvent() *v11.VersionHistoryItem {
	if m != nil {
		return m.EndEvent
	}
	return nil
}

type ShardOwnershipLostError struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShardOwnershipLostError) Reset()         { *m = ShardOwnershipLostError{} }
func (m *ShardOwnershipLostError) String() string { return proto.CompactTextString(m) }
func (*ShardOwnershipLostError) ProtoMessage()    {}
func (*ShardOwnershipLostError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{5}
}
func (m *ShardOwnershipLostError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ShardOwnershipLostError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ShardOwnershipLostError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ShardOwnershipLostError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShardOwnershipLostError.Merge(m, src)
}
func (m *ShardOwnershipLostError) XXX_Size() int {
	return m.Size()
}
func (m *ShardOwnershipLostError) XXX_DiscardUnknown() {
	xxx_messageInfo_ShardOwnershipLostError.DiscardUnknown(m)
}

var xxx_messageInfo_ShardOwnershipLostError proto.InternalMessageInfo

func (m *ShardOwnershipLostError) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type TaskListNotOwnedByHostError struct {
	OwnedByIdentity      string   `protobuf:"bytes,1,opt,name=owned_by_identity,json=ownedByIdentity,proto3" json:"owned_by_identity,omitempty"`
	MyIdentity           string   `protobuf:"bytes,2,opt,name=my_identity,json=myIdentity,proto3" json:"my_identity,omitempty"`
	TaskListName         string   `protobuf:"bytes,3,opt,name=task_list_name,json=taskListName,proto3" json:"task_list_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskListNotOwnedByHostError) Reset()         { *m = TaskListNotOwnedByHostError{} }
func (m *TaskListNotOwnedByHostError) String() string { return proto.CompactTextString(m) }
func (*TaskListNotOwnedByHostError) ProtoMessage()    {}
func (*TaskListNotOwnedByHostError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{6}
}
func (m *TaskListNotOwnedByHostError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TaskListNotOwnedByHostError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TaskListNotOwnedByHostError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TaskListNotOwnedByHostError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskListNotOwnedByHostError.Merge(m, src)
}
func (m *TaskListNotOwnedByHostError) XXX_Size() int {
	return m.Size()
}
func (m *TaskListNotOwnedByHostError) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskListNotOwnedByHostError.DiscardUnknown(m)
}

var xxx_messageInfo_TaskListNotOwnedByHostError proto.InternalMessageInfo

func (m *TaskListNotOwnedByHostError) GetOwnedByIdentity() string {
	if m != nil {
		return m.OwnedByIdentity
	}
	return ""
}

func (m *TaskListNotOwnedByHostError) GetMyIdentity() string {
	if m != nil {
		return m.MyIdentity
	}
	return ""
}

func (m *TaskListNotOwnedByHostError) GetTaskListName() string {
	if m != nil {
		return m.TaskListName
	}
	return ""
}

type SemaphoreNotOwnedByHostError struct {
	OwnedByIdentity      string   `protobuf:"bytes,1,opt,name=owned_by_identity,json=ownedByIdentity,proto3" json:"owned_by_identity,omitempty"`
	MyIdentity           string   `protobuf:"bytes,2,opt,name=my_identity,json=myIdentity,proto3" json:"my_identity,omitempty"`
	BucketId             string   `protobuf:"bytes,3,opt,name=bucket_id,json=bucketId,proto3" json:"bucket_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SemaphoreNotOwnedByHostError) Reset()         { *m = SemaphoreNotOwnedByHostError{} }
func (m *SemaphoreNotOwnedByHostError) String() string { return proto.CompactTextString(m) }
func (*SemaphoreNotOwnedByHostError) ProtoMessage()    {}
func (*SemaphoreNotOwnedByHostError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3688ca0fd170c8f9, []int{7}
}
func (m *SemaphoreNotOwnedByHostError) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SemaphoreNotOwnedByHostError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SemaphoreNotOwnedByHostError.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SemaphoreNotOwnedByHostError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SemaphoreNotOwnedByHostError.Merge(m, src)
}
func (m *SemaphoreNotOwnedByHostError) XXX_Size() int {
	return m.Size()
}
func (m *SemaphoreNotOwnedByHostError) XXX_DiscardUnknown() {
	xxx_messageInfo_SemaphoreNotOwnedByHostError.DiscardUnknown(m)
}

var xxx_messageInfo_SemaphoreNotOwnedByHostError proto.InternalMessageInfo

func (m *SemaphoreNotOwnedByHostError) GetOwnedByIdentity() string {
	if m != nil {
		return m.OwnedByIdentity
	}
	return ""
}

func (m *SemaphoreNotOwnedByHostError) GetMyIdentity() string {
	if m != nil {
		return m.MyIdentity
	}
	return ""
}

func (m *SemaphoreNotOwnedByHostError) GetBucketId() string {
	if m != nil {
		return m.BucketId
	}
	return ""
}

func init() {
	proto.RegisterType((*CurrentBranchChangedError)(nil), "uber.cadence.shared.v1.CurrentBranchChangedError")
	proto.RegisterType((*InternalDataInconsistencyError)(nil), "uber.cadence.shared.v1.InternalDataInconsistencyError")
	proto.RegisterType((*EventAlreadyStartedError)(nil), "uber.cadence.shared.v1.EventAlreadyStartedError")
	proto.RegisterType((*RemoteSyncMatchedError)(nil), "uber.cadence.shared.v1.RemoteSyncMatchedError")
	proto.RegisterType((*RetryTaskV2Error)(nil), "uber.cadence.shared.v1.RetryTaskV2Error")
	proto.RegisterType((*ShardOwnershipLostError)(nil), "uber.cadence.shared.v1.ShardOwnershipLostError")
	proto.RegisterType((*TaskListNotOwnedByHostError)(nil), "uber.cadence.shared.v1.TaskListNotOwnedByHostError")
	proto.RegisterType((*SemaphoreNotOwnedByHostError)(nil), "uber.cadence.shared.v1.SemaphoreNotOwnedByHostError")
}

func init() {
	proto.RegisterFile("uber/cadence/shared/v1/error.proto", fileDescriptor_3688ca0fd170c8f9)
}

var fileDescriptor_3688ca0fd170c8f9 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xc1, 0x6e, 0xd3, 0x4c,
	0x14, 0x85, 0xe5, 0xfe, 0x3f, 0xa8, 0x99, 0x56, 0x40, 0xad, 0xaa, 0x84, 0x16, 0x85, 0xc8, 0x20,
	0x54, 0x58, 0xd8, 0xa4, 0x88, 0x15, 0x2b, 0x1a, 0x82, 0x6a, 0xd4, 0x82, 0xe4, 0x94, 0x22, 0xb1,
	0xb1, 0xc6, 0x33, 0x97, 0x78, 0x94, 0xcc, 0x4c, 0x34, 0x73, 0x93, 0xe0, 0x37, 0x60, 0xc9, 0x9a,
	0x27, 0x62, 0xc9, 0x23, 0xa0, 0x3c, 0x09, 0x1a, 0x8f, 0x43, 0x9b, 0xee, 0x58, 0xb0, 0x4b, 0xee,
	0xfd, 0xce, 0xf1, 0xf1, 0x91, 0x2f, 0x89, 0x66, 0x05, 0x98, 0x84, 0x51, 0x0e, 0x8a, 0x41, 0x62,
	0x4b, 0x6a, 0x80, 0x27, 0xf3, 0x5e, 0x02, 0xc6, 0x68, 0x13, 0x4f, 0x8d, 0x46, 0x1d, 0xee, 0x39,
	0x26, 0x6e, 0x98, 0xd8, 0x33, 0xf1, 0xbc, 0xb7, 0xdf, 0x5d, 0xd3, 0xd2, 0xa9, 0x70, 0x42, 0xa6,
	0xa5, 0xd4, 0xca, 0x2b, 0xf7, 0x1f, 0xae, 0x13, 0x5c, 0x0a, 0xe5, 0x98, 0x52, 0x58, 0xd4, 0xa6,
	0xf2, 0x50, 0x74, 0x46, 0xee, 0xf5, 0x67, 0xc6, 0x80, 0xc2, 0x63, 0x43, 0x15, 0x2b, 0xfb, 0x25,
	0x55, 0x23, 0xe0, 0x03, 0x97, 0x20, 0x7c, 0x46, 0x76, 0x99, 0x5f, 0xe6, 0x45, 0xbd, 0xcd, 0x51,
	0x8f, 0x41, 0xb5, 0x83, 0x6e, 0x70, 0xb8, 0x9d, 0x85, 0xec, 0xaa, 0xf0, 0xdc, 0x6d, 0xa2, 0x2e,
	0xe9, 0xa4, 0x0a, 0xc1, 0x28, 0x3a, 0x79, 0x4d, 0x91, 0xa6, 0x8a, 0x69, 0x65, 0x85, 0x45, 0x50,
	0xac, 0xaa, 0x3d, 0xa3, 0x7d, 0xd2, 0x1e, 0xcc, 0x41, 0xe1, 0xab, 0x89, 0x01, 0xca, 0xab, 0x21,
	0x52, 0x83, 0xcd, 0xf3, 0xa2, 0x36, 0xd9, 0xcb, 0x40, 0x6a, 0x84, 0x61, 0xa5, 0xd8, 0x19, 0x45,
	0x56, 0xae, 0x36, 0xdf, 0x37, 0xc8, 0x9d, 0x0c, 0xd0, 0x54, 0xe7, 0xd4, 0x8e, 0x2f, 0x8e, 0x7c,
	0xbc, 0x03, 0xd2, 0xe2, 0x5a, 0x52, 0xa1, 0x72, 0xc1, 0xeb, 0x4c, 0xad, 0x6c, 0xd3, 0x0f, 0x52,
	0x1e, 0x7e, 0x20, 0xe1, 0x42, 0x9b, 0xf1, 0xe7, 0x89, 0x5e, 0xe4, 0xf0, 0x05, 0xd8, 0x0c, 0x85,
	0x56, 0xed, 0x8d, 0x6e, 0x70, 0xb8, 0x75, 0xf4, 0x38, 0x5e, 0x2b, 0x95, 0x4e, 0x45, 0x3c, 0xef,
	0xc5, 0x1f, 0x1b, 0x7c, 0xb0, 0xa2, 0xb3, 0x9d, 0xc5, 0xf5, 0x51, 0xf8, 0x96, 0x6c, 0x59, 0x17,
	0x39, 0x07, 0xf7, 0x12, 0xed, 0xff, 0x6a, 0xbf, 0x27, 0xd7, 0xfc, 0x5c, 0xd5, 0xce, 0xf1, 0x02,
	0x8c, 0x15, 0x5a, 0x9d, 0xf8, 0xc6, 0x53, 0x04, 0x99, 0x91, 0x5a, 0x5d, 0x37, 0x10, 0xbe, 0x21,
	0x2d, 0x50, 0xbc, 0x71, 0xfa, 0xff, 0x6f, 0x9d, 0x36, 0x41, 0xf1, 0xda, 0x27, 0x4a, 0xc8, 0xdd,
	0x61, 0x49, 0x0d, 0x7f, 0xbf, 0x50, 0x60, 0x6c, 0x29, 0xa6, 0xa7, 0xda, 0xa2, 0xaf, 0x68, 0x97,
	0xdc, 0xd0, 0x6e, 0xda, 0xd4, 0xe3, 0xff, 0x44, 0xdf, 0x02, 0x72, 0xe0, 0x8a, 0x3c, 0x15, 0x16,
	0xdf, 0x69, 0x74, 0x3a, 0x7e, 0x5c, 0x9d, 0xfc, 0x51, 0x3d, 0x25, 0x3b, 0x0e, 0xe4, 0x79, 0x51,
	0xe5, 0x82, 0x83, 0x42, 0x81, 0x55, 0xe3, 0x70, 0x5b, 0x7b, 0x38, 0x6d, 0xc6, 0xe1, 0x03, 0xb2,
	0x25, 0xaf, 0x50, 0x1b, 0x35, 0x45, 0xe4, 0x25, 0xf0, 0x88, 0xdc, 0x42, 0x6a, 0xc7, 0xf9, 0x44,
	0x58, 0xcc, 0x15, 0x95, 0x50, 0x97, 0xd6, 0xca, 0xb6, 0x71, 0x95, 0x80, 0x4a, 0x88, 0xbe, 0x06,
	0xe4, 0xfe, 0x10, 0x24, 0x9d, 0x96, 0xda, 0xc0, 0x3f, 0xcf, 0x74, 0x40, 0x5a, 0xc5, 0x8c, 0x8d,
	0x01, 0xdd, 0x97, 0xe3, 0xe3, 0x6c, 0xfa, 0x41, 0xca, 0x8f, 0xfb, 0x3f, 0x96, 0x9d, 0xe0, 0xe7,
	0xb2, 0x13, 0xfc, 0x5a, 0x76, 0x82, 0x4f, 0x2f, 0x46, 0x02, 0xcb, 0x59, 0x11, 0x33, 0x2d, 0x93,
	0xb5, 0x83, 0x8a, 0x47, 0xa0, 0x92, 0xfa, 0x88, 0x2e, 0x2f, 0xf7, 0xa5, 0xff, 0x35, 0xef, 0x15,
	0x37, 0xeb, 0xcd, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x98, 0x7b, 0x9b, 0xe3, 0x03,
	0x00, 0x00,
}

func (m *CurrentBranchChangedError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CurrentBranchChangedError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CurrentBranchChangedError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.CurrentBranchToken) > 0 {
		i -= len(m.CurrentBranchToken)
		copy(dAtA[i:], m.CurrentBranchToken)
		i = encodeVarintError(dAtA, i, uint64(len(m.CurrentBranchToken)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *InternalDataInconsistencyError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InternalDataInconsistencyError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *InternalDataInconsistencyError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *EventAlreadyStartedError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAlreadyStartedError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAlreadyStartedError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *RemoteSyncMatchedError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoteSyncMatchedError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoteSyncMatchedError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	return len(dAtA) - i, nil
}

func (m *RetryTaskV2Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RetryTaskV2Error) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RetryTaskV2Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.EndEvent != nil {
		{
			size, err := m.EndEvent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintError(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.StartEvent != nil {
		{
			size, err := m.StartEvent.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintError(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.WorkflowExecution != nil {
		{
			size, err := m.WorkflowExecution.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintError(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DomainId) > 0 {
		i -= len(m.DomainId)
		copy(dAtA[i:], m.DomainId)
		i = encodeVarintError(dAtA, i, uint64(len(m.DomainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ShardOwnershipLostError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ShardOwnershipLostError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ShardOwnershipLostError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintError(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TaskListNotOwnedByHostError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TaskListNotOwnedByHostError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TaskListNotOwnedByHostError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.TaskListName) > 0 {
		i -= len(m.TaskListName)
		copy(dAtA[i:], m.TaskListName)
		i = encodeVarintError(dAtA, i, uint64(len(m.TaskListName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MyIdentity) > 0 {
		i -= len(m.MyIdentity)
		copy(dAtA[i:], m.MyIdentity)
		i = encodeVarintError(dAtA, i, uint64(len(m.MyIdentity)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnedByIdentity) > 0 {
		i -= len(m.OwnedByIdentity)
		copy(dAtA[i:], m.OwnedByIdentity)
		i = encodeVarintError(dAtA, i, uint64(len(m.OwnedByIdentity)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SemaphoreNotOwnedByHostError) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SemaphoreNotOwnedByHostError) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SemaphoreNotOwnedByHostError) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.BucketId) > 0 {
		i -= len(m.BucketId)
		copy(dAtA[i:], m.BucketId)
		i = encodeVarintError(dAtA, i, uint64(len(m.BucketId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.MyIdentity) > 0 {
		i -= len(m.MyIdentity)
		copy(dAtA[i:], m.MyIdentity)
		i = encodeVarintError(dAtA, i, uint64(len(m.MyIdentity)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnedByIdentity) > 0 {
		i -= len(m.OwnedByIdentity)
		copy(dAtA[i:], m.OwnedByIdentity)
		i = encodeVarintError(dAtA, i, uint64(len(m.OwnedByIdentity)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintError(dAtA []byte, offset int, v uint64) int {
	offset -= sovError(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CurrentBranchChangedError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.CurrentBranchToken)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InternalDataInconsistencyError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EventAlreadyStartedError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RemoteSyncMatchedError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *RetryTaskV2Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DomainId)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	if m.WorkflowExecution != nil {
		l = m.WorkflowExecution.Size()
		n += 1 + l + sovError(uint64(l))
	}
	if m.StartEvent != nil {
		l = m.StartEvent.Size()
		n += 1 + l + sovError(uint64(l))
	}
	if m.EndEvent != nil {
		l = m.EndEvent.Size()
		n += 1 + l + sovError(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ShardOwnershipLostError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TaskListNotOwnedByHostError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnedByIdentity)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	l = len(m.MyIdentity)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	l = len(m.TaskListName)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *SemaphoreNotOwnedByHostError) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnedByIdentity)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	l = len(m.MyIdentity)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	l = len(m.BucketId)
	if l > 0 {
		n += 1 + l + sovError(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovError(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozError(x uint64) (n int) {
	return sovError(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CurrentBranchChangedError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CurrentBranchChangedError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CurrentBranchChangedError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentBranchToken", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentBranchToken = append(m.CurrentBranchToken[:0], dAtA[iNdEx:postIndex]...)
			if m.CurrentBranchToken == nil {
				m.CurrentBranchToken = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InternalDataInconsistencyError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InternalDataInconsistencyError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InternalDataInconsistencyError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventAlreadyStartedError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAlreadyStartedError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAlreadyStartedError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoteSyncMatchedError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoteSyncMatchedError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoteSyncMatchedError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RetryTaskV2Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RetryTaskV2Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RetryTaskV2Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DomainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DomainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkflowExecution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WorkflowExecution == nil {
				m.WorkflowExecution = &v1.WorkflowExecution{}
			}
			if err := m.WorkflowExecution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartEvent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StartEvent == nil {
				m.StartEvent = &v11.VersionHistoryItem{}
			}
			if err := m.StartEvent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndEvent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EndEvent == nil {
				m.EndEvent = &v11.VersionHistoryItem{}
			}
			if err := m.EndEvent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ShardOwnershipLostError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ShardOwnershipLostError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ShardOwnershipLostError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TaskListNotOwnedByHostError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TaskListNotOwnedByHostError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TaskListNotOwnedByHostError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnedByIdentity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnedByIdentity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MyIdentity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MyIdentity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskListName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskListName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SemaphoreNotOwnedByHostError) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowError
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SemaphoreNotOwnedByHostError: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SemaphoreNotOwnedByHostError: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnedByIdentity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnedByIdentity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MyIdentity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MyIdentity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BucketId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowError
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthError
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthError
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BucketId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipError(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthError
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipError(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowError
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowError
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowError
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthError
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupError
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthError
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthError        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowError          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupError = fmt.Errorf("proto: unexpected end of group")
)
